id = "redis-01"
image = "docker.io/library/redis:4.0-alpine"

[[networks]]
	type = "macvlan"
	name = "ob0"
	[networks.ipam]
		type = "dhcp"

[resources]
	cpu = 1.5
	memory = 64

services = ["redis.io"]
