id = "systemd"
image = "registry.service.aegis/systemd:18.10"
network = "cni"

caps = [
	"CAP_SYS_ADMIN",
	"CAP_NET_ADMIN",
	"CAP_CHOWN",
	"CAP_DAC_OVERRIDE",
	"CAP_FSETID",
	"CAP_FOWNER",
	"CAP_MKNOD",
	"CAP_NET_RAW",
	"CAP_SETGID",
	"CAP_SETUID",
	"CAP_SETFCAP",
	"CAP_SETPCAP",
	"CAP_NET_BIND_SERVICE",
	"CAP_SYS_CHROOT",
	"CAP_KILL",
	"CAP_AUDIT_WRITE",

	"CAP_IPC_LOCK",
	"CAP_IPC_OWNER",
	"CAP_SYS_MODULE",

	"CAP_SYS_PTRACE",
	"CAP_SYS_PACCT",

	"CAP_SYS_NICE",

	"CAP_SYS_RESOURCE",

	#CAP_SYS_TIME = Cap(25)

	"CAP_SYS_TTY_CONFIG",

	"CAP_LEASE",

	"CAP_AUDIT_CONTROL",


]
