version = "v5"
base = "docker.io/stellarproject/ubuntu:18.10"
kernel = "5.0.7"
init = "/sbin/init"

userland = """
RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y \
	libnl-3-dev \
	libnet-dev \
	libprotobuf-dev \
	pigz

RUN systemctl enable serial-getty@ttyS0.service

RUN rm /etc/update-motd.d/*
ADD os/motd/* /etc/update-motd.d/
"""

[[components]]
	name = "node_exporter"
	systemd = true
[[components]]
	name = "criu"
[[components]]
	name = "cni"
[[components]]
	name = "buildkit"
	systemd = true
[[components]]
	name = "vab"
[[components]]
	name = "containerd"
	systemd = true
[[components]]
	name = "orbit"
[[components]]
	name = "terra"
