hostname = "terra-01"
mac = "xx:xx:xx:xx:xx:xx"
image = "docker.io/stellarproject/example:6"

[[groups]]
  label = "os"
  type = "single"
  stage = "stage1"

  [[groups.disk]]
    device = "/dev/sda"
    size = 2048
