hostname = "terra-01"
mac = "xx:xx:xx:xx:xx:xx"
image = "docker.io/stellarproject/example:6"

[[groups]]
  label = "os"
  type = "single"
  stage = "stage1"

  [[groups.disk]]
    device = "/dev/sda1"
    size = 0

[[groups]]
  label = "data"
  type = "single"
  stage = "stage1"

  [[groups.subvolumes]]
    name = "data"
    path = "/var/lib/containerd"

  [[groups.disk]]
    device = "/dev/sdb"
