hostname = "terra-01"
mac = "xx:xx:xx:xx:xx:xx"
image = "docker.io/stellarproject/example:9"

[[volumes]]
  label = "os"
  fs_type = "ext4"
  mbr = true

  [[volumes.disk]]
    device = "/dev/sda"
    size = 2048
