hostname = "example"
version = "6"
os = "docker.io/stellarproject/terraos:v11"
repo = "docker.io/stellarproject"
userland = """
RUN echo 'terra:terra' | chpasswd
ADD sshd_config /etc/ssh/
"""

[netplan]
  [[netplan.interfaces]]
    name = "eth0"

[resolvconf]
  nameservers = ["8.8.8.8", "8.8.4.4"]
