hostname = "example"
version = "5"
os = "docker.io/stellarproject/terraos:v10"
repo = "docker.io/stellarproject"
userland = """
RUN echo 'terra:terra' | chpasswd
"""
[netplan]
  [[netplan.interfaces]]
    name = "eth0"

[resolvconf]
  nameservers = ["8.8.8.8", "8.8.4.4"]
