hostname = "terra-01"
labels = ["testing", "example"]
memory = 4096
domain = "home"
gateway = "10.0.10.1"
nameservers = []
cluster_fs = ""

[[nic]]
  name = "eth0"
  mac = "xx:xx:xx:xx:xx:xx"
  addresses = []
  speed = 1000

[[volumes]]
  label = "os"
  type = "btrfs"
  boot = true
  path = "/"

[[gpus]]
  model = "Geforce Titian X"
  cores = 6400
  memory = 12000
  capabilities = ["compute", "video"]

[[cpus]]
  ghz = 3.4

[[cpus]]
  ghz = 3.4

[image]
  name = "registry.compute:5000/example:11"
  base = "registry.compute:5000/terraos:v16-dev"
  init = "/sbin/init"
  userland = """
RUN echo 'terra:terra' | chpasswd
ADD sshd_config /etc/ssh/
"""
