root = "/var/lib/containerd"
state = "/run/containerd"
oom_score = -50

disabled_plugins = [
	"cri",
	"btrfs",
	"zfs",
	"aufs",
	"restart",
]

[grpc]
  address = "/run/containerd/containerd.sock"
  tcp_address = "0.0.0.0:9100"

[debug]
  level = "debug"

[metrics]
  address = "0.0.0.0:9200"
  grpc_histogram = true

[cgroup]
  path = ""

[plugins]
  [plugins.bolt]
    content_sharing_policy = "shared"
  [plugins.cgroups]
    no_prometheus = false
  [plugins.diff-service]
    default = ["walking"]
  [plugins.opt]
    path = "/opt/containerd"
  [plugins.scheduler]
    pause_threshold = 0.02
    deletion_threshold = 0
    mutation_threshold = 100
    schedule_delay = "0s"
    startup_delay = "100ms"
  [plugins.task]
    platforms = ["linux/amd64"]
  [plugins."stellarproject.io/orbit"]
    interval = "10s"
  [plugins."stellarproject.io/store"]
    master = ""
